[package]
name = "ai-compiler"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
itertools = "0.14.0"
pastey = "0.1.1"
thiserror = "2.0.17"
unicode-segmentation = "1.12.0"
