[package]
name = "ailang-py"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "ailangpy"
crate-type = ["cdylib"]

[dependencies]
ailang = { version = "0.1.0", path = "../ai-compiler" }
pyo3 = "0.27"
